[build]
  command = "CI=false DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  PUBLIC_URL = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false 